version: "3.9"

services:
  web:
    build: .
    container_name: pizza_hub_app
    command: bash -c "python manage.py makemigrations && python manage.py migrate && uvicorn pizza_hub.asgi:django_app --host 0.0.0.0 --reload"
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - pizza_network
    volumes:
      - .:/app

  db:
    image: postgres:15
    container_name: postgres_db

    environment:
      POSTGRES_DB: pizza_hub
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - pizza_network
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:

networks:
  pizza_network:
    driver: bridge
