# Generated by Django 5.1.7 on 2025-04-01 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_hub_app', '0002_alter_product_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='refresh_token',
            field=models.CharField(default=None, max_length=300, null=True, unique=True),
        ),
    ]
