# Generated by Django 5.1.7 on 2025-04-09 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_hub_app', '0002_rename_desription_category_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ingredients',
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
