# Generated by Django 5.1.7 on 2025-04-09 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_hub_app', '0003_remove_product_ingredients_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='image',
            field=models.ImageField(upload_to='media/upload_product_image/'),
        ),
    ]
