# Generated by Django 5.1.7 on 2025-04-09 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_hub_app', '0004_alter_category_description_alter_productimages_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_category', to='pizza_hub_app.product'),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='image',
            field=models.ImageField(upload_to='upload_product_image/'),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='pizza_hub_app.product'),
        ),
        migrations.AlterField(
            model_name='productingredients',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_ingredients', to='pizza_hub_app.product'),
        ),
        migrations.DeleteModel(
            name='ProductPayment',
        ),
    ]
