# Generated by Django 5.1.7 on 2025-04-06 14:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_hub_app', '0004_alter_user_address_alter_user_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlackListToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(default=None, unique=True)),
                ('is_valid', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField(default=None)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza_hub_app.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
