# Generated by Django 5.1.7 on 2025-04-06 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_hub_app', '0005_blacklisttoken'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blacklisttoken',
            options={'verbose_name_plural': 'BlackListedTokens'},
        ),
        migrations.AlterModelTable(
            name='blacklisttoken',
            table='BlackListedToken',
        ),
    ]
