# Generated by Django 5.1.7 on 2025-04-15 22:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_hub_app', '0006_alter_cart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinstance',
            name='order',
        ),
        migrations.AlterField(
            model_name='productinstanceingredients',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pizza_hub_app.ingredients'),
        ),
        migrations.AlterField(
            model_name='productinstanceingredients',
            name='product_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pizza_hub_app.productinstance'),
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza_hub_app.order')),
                ('product_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza_hub_app.productinstance')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
