# Generated by Django 5.1.7 on 2025-04-15 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_hub_app', '0007_remove_productinstance_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproductinstance',
            name='is_current',
            field=models.BooleanField(default=True),
        ),
    ]
