# Generated by Django 5.1.7 on 2025-04-15 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_hub_app', '0008_cartproductinstance_is_current'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='cart',
            field=models.OneToOneField(blank=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='pizza_hub_app.cart'),
        ),
    ]
