# Generated by Django 5.1.7 on 2025-04-15 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_hub_app', '0009_remove_cart_user_user_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproductinstance',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_product_instance', to='pizza_hub_app.cart'),
        ),
    ]
