# Generated by Django 5.1.7 on 2025-04-16 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_hub_app', '0010_alter_cartproductinstance_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproductinstance',
            name='product_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_instance', to='pizza_hub_app.productinstance'),
        ),
    ]
