# Generated by Django 5.1.7 on 2025-04-16 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_hub_app', '0011_alter_cartproductinstance_product_instance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinstanceingredients',
            name='product_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_instance_ingredients', to='pizza_hub_app.productinstance'),
        ),
    ]
