# Generated by Django 5.1.7 on 2025-04-16 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_hub_app', '0012_alter_productinstanceingredients_product_instance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinstanceingredients',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingredient', to='pizza_hub_app.ingredients'),
        ),
    ]
